#!/usr/bin/env python3
"""One-off generator: writes worldcup_pool/data/wc2026_top_scorer_candidates.json (25 names × 48 WC2026 TLAs)."""

from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO))

from worldcup_pool.wc2026_official_groups import official_wc2026_group_teams  # noqa: E402


def main() -> None:
    codes = sorted({c for teams in official_wc2026_group_teams().values() for c, _ in teams})
    assert len(codes) == 48

    # Curated attacker-weighted lists (recent call-ups / public squad reporting). Not official FIFA lists.
    pools: dict[str, list[str]] = {
        "ALG": [
            "Riyad Mahrez",
            "Baghdad Bounedjah",
            "Islam Slimani",
            "Adam Ounas",
            "Amine Gouiri",
            "Ramy Bensebaini",
            "Youcef Atal",
            "Said Benrahma",
            "Andy Delort",
            "Hicham Boudaoui",
            "Ismaël Bennacer",
            "Farès Chaïbi",
            "Michael Gregoritsch",
            "Abde Rebbach",
            "Jaouen Hadjam",
            "Nabil Bentaleb",
            "Youcef Belaïli",
            "Mohamed Amoura",
            "Yacine Brahimi",
            "Rachid Ghezzal",
            "Aissa Mandi",
            "Elias Bendebka",
            "Houssam Mrezigue",
            "Adil Aouchiche",
            "Monsef Bakrar",
        ],
        "ARG": [
            "Lionel Messi",
            "Lautaro Martínez",
            "Julián Álvarez",
            "Ángel Di María",
            "Paulo Dybala",
            "Nicolás González",
            "Giovani Lo Celso",
            "Enzo Fernández",
            "Rodrigo De Paul",
            "Leandro Paredes",
            "Álexis Mac Allister",
            "Lucas Ocampos",
            "Alejandro Garnacho",
            "Nicolás Otamendi",
            "Lisandro Martínez",
            "Exequiel Palacios",
            "Thiago Almada",
            "Valentín Carboni",
            "Facundo Buonanotte",
            "Matías Soulé",
            "Nico Paz",
            "Luka Romero",
            "Ezequiel Fernández",
            "Benjamín Rollheiser",
            "Ángel Correa",
        ],
        "AUS": [
            "Mitchell Duke",
            "Harry Souttar",
            "Mathew Leckie",
            "Craig Goodwin",
            "Awer Mabil",
            "Martin Boyle",
            "Jamie Maclaren",
            "Nestory Irankunda",
            "John Iredale",
            "Kusini Yengi",
            "Patrick Yazbek",
            "Jackson Irvine",
            "Connor Metcalfe",
            "Riley McGree",
            "Keanu Baccus",
            "Denis Genreau",
            "Joshua Nisbet",
            "Sam Silvera",
            "Bruno Fornaroli",
            "Adam Taggart",
            "Brandon Borrello",
            "Marco Tilio",
            "Mohamed Toure",
            "Johnny Warren",
            "Fabian Cavallo",
        ],
        "AUT": [
            "Marko Arnautović",
            "Michael Gregoritsch",
            "Sasa Kalajdzic",
            "Marcel Sabitzer",
            "Konrad Laimer",
            "Christoph Baumgartner",
            "Xaver Schlager",
            "Florian Grillitsch",
            "Romano Schmid",
            "Patrick Wimmer",
            "Nicolas Seiwald",
            "Maximilian Wöber",
            "David Alaba",
            "Philipp Lienhart",
            "Stefan Posch",
            "Kevin Danso",
            "Gernot Trauner",
            "Marco Friedl",
            "Alexander Prass",
            "Andreas Weimann",
            "Guido Burgstaller",
            "Junior Adamu",
            "Yusuf Demir",
            "Reda Khadra",
            "Tai Baribo",
        ],
        "BEL": [
            "Romelu Lukaku",
            "Kevin De Bruyne",
            "Leandro Trossard",
            "Dodi Lukebakio",
            "Jeremy Doku",
            "Charles De Ketelaere",
            "Amadou Onana",
            "Youri Tielemans",
            "Arthur Theate",
            "Jan Vertonghen",
            "Thorgan Hazard",
            "Axel Witsel",
            "Hans Vanaken",
            "Orel Mangala",
            "Lois Openda",
            "Michy Batshuayi",
            "Yannick Carrasco",
            "Timothy Castagne",
            "Thomas Meunier",
            "Zeno Debast",
            "Wout Faes",
            "Mike Trésor",
            "Johan Bakayoko",
            "Arnaud Kalimuendo",
            "Alexis Saelemaekers",
        ],
        "BIH": [
            "Edin Džeko",
            "Ermedin Demirović",
            "Smail Prevljak",
            "Amar Dedić",
            "Rade Krunić",
            "Miralem Pjanić",
            "Dennis Hadžikadunić",
            "Sebastian Szymański",
            "Dino Bešović",
            "Benjamin Tahirović",
            "Haris Tabaković",
            "Luka Menalo",
            "Jusuf Gazibegović",
            "Nikola Katić",
            "Ivan Šunjić",
            "Gojko Cimirot",
            "Hamza Čataković",
            "Tarik Škiljo",
            "Stjepan Radeljić",
            "Adis Jahić",
            "Luka Jurčić",
            "Dario Šarić",
            "Sanjin Prcić",
            "Emir Karić",
            "Muharem Čekić",
        ],
        "BRA": [
            "Vinícius Júnior",
            "Neymar",
            "Richarlison",
            "Gabriel Jesus",
            "Rodrygo",
            "Raphinha",
            "Gabriel Martinelli",
            "Endrick",
            "Matheus Cunha",
            "João Pedro",
            "Evanilson",
            "Bruno Guimarães",
            "Lucas Paquetá",
            "Casemiro",
            "André",
            "Douglas Luiz",
            "Gabriel Magalhães",
            "Marquinhos",
            "Éder Militão",
            "Bremer",
            "Danilo",
            "Wendell",
            "João Gomes",
            "Savinho",
            "Luiz Henrique",
        ],
        "CAN": [
            "Jonathan David",
            "Cyle Larin",
            "Alphonso Davies",
            "Stephen Eustáquio",
            "Tajon Buchanan",
            "Lucas Cavallini",
            "Jacen Russell-Rowe",
            "Iké Ugbo",
            "Liam Millar",
            "Junior Hoilett",
            "Sam Adekugbe",
            "Alistair Johnston",
            "Kamal Miller",
            "Richie Laryea",
            "Mark-Anthony Kaye",
            "Ismaël Koné",
            "Mathieu Choinière",
            "Liam Fraser",
            "David Wotherspoon",
            "Jonathan Osorio",
            "Mohamed Farsi",
            "Dayne St. Clair",
            "Milan Borjan",
            "James Pantemis",
            "Ayo Akinola",
        ],
        "COL": [
            "Luis Díaz",
            "James Rodríguez",
            "Rafael Santos Borré",
            "Jhon Arias",
            "Luis Sinisterra",
            "Jhon Durán",
            "Roger Martínez",
            "Jefferson Lerma",
            "Richard Ríos",
            "Jorge Carrascal",
            "Mateus Uribe",
            "Jefferson Cuero",
            "Miguel Borja",
            "Kevin Castaño",
            "Steven Alzate",
            "Jéfferson Campáz",
            "Cucho Hernández",
            "Daniel Ruiz",
            "Cristian Arango",
            "Santiago Arias",
            "Davinson Sánchez",
            "Carlos Cuesta",
            "Yerson Mosquera",
            "Jhon Lucumí",
            "Jhon Jáder Durán",
        ],
        "CPV": [
            "Ryan Mendes",
            "Garry Rodrigues",
            "Júlio Tavares",
            "Jamiro Monteiro",
            "Kenny Rocha Santos",
            "Willy Semedo",
            "Steven Fortes",
            "Lisandro Semedo",
            "Deroy Duarte",
            "Dylan Tavares",
            "João Paulo Fernandes",
            "Keven Santos",
            "Vagner Gonçalves",
            "Jovane Cabral",
            "Llyod Semedo",
            "Patrick Andrade",
            "Gilson Tavares",
            "Bryan Duarte",
            "Wilton Semedo",
            "Hélder Costa",
            "Yannick Semedo",
            "Mesaque Dju",
            "Rodney Antunes",
            "Diney Borges",
            "Stopira",
        ],
        "CIV": [
            "Sébastien Haller",
            "Nicolas Pépé",
            "Jonathan Bamba",
            "Wilfried Zaha",
            "Simon Adingra",
            "Jérémie Boga",
            "Franck Kessié",
            "Ibrahim Sangaré",
            "Jean-Michaël Seri",
            "Max Gradel",
            "Christian Kouamé",
            "Oumar Diakité",
            "Evan Ndicka",
            "Odilon Kossounou",
            "Wilfried Singo",
            "Ghislain Konan",
            "Eric Bailly",
            "Serge Aurier",
            "Karim Konaté",
            "Hamed Traorè",
            "Jean Philippe Krasso",
            "Marwan Attia",
            "Emam Ashour",
            "Mohamed Bamba",
            "Lazan Amani",
        ],
        "COD": [
            "Yoane Wissa",
            "Cédric Bakambu",
            "Fiston Mayele",
            "Théo Bongonda",
            "Gaël Kakuta",
            "Chancel Mbemba",
            "Arthur Masuaku",
            "Meschack Elia",
            "Silas Katompa",
            "Samuel Moutoussamy",
            "Charles Pickel",
            "Aaron Tshibola",
            "Gédéon Kalulu",
            "Grady Diangana",
            "Ben Malango",
            "Paul-José Mpoku",
            "Jackson Muleka",
            "Simon Banza",
            "Jonathan Bolingi",
            "Britt Assombalonga",
            "Joris Kayembe",
            "Rocky Bushiri",
            "Dylan Batubinsika",
            "Paulinho",
            "Dieumerci Mbokani",
        ],
        "CRO": [
            "Luka Modrić",
            "Ivan Perišić",
            "Andrej Kramarić",
            "Marcelo Brozović",
            "Mateo Kovačić",
            "Mario Pašalić",
            "Bruno Petković",
            "Ante Budimir",
            "Nikola Vlašić",
            "Luka Sučić",
            "Marko Livaja",
            "Kristijan Jakić",
            "Josip Juranović",
            "Joško Gvardiol",
            "Borna Sosa",
            "Domagoj Vida",
            "Josip Stanišić",
            "Marin Pongračić",
            "Borna Barišić",
            "Martin Erlić",
            "Petar Musa",
            "Dion Drena Beljo",
            "Dario Špikić",
            "Luka Ivanušec",
            "Toni Fruk",
        ],
        "CZE": [
            "Patrik Schick",
            "Adam Hložek",
            "Jan Kuchta",
            "Vladimír Coufal",
            "Tomáš Souček",
            "Antonín Barák",
            "Alex Král",
            "Ondřej Lingr",
            "Mojmír Chytil",
            "Ondřej Červinka",
            "Václav Černý",
            "Ladislav Krejčí",
            "David Zima",
            "Tomáš Vlček",
            "Robin Hranáč",
            "David Jurásek",
            "Ladislav Takács",
            "Matěj Kovář",
            "Vítězslav Jaroš",
            "Jindřich Staněk",
            "Tomáš Chorý",
            "Matej Jurásek",
            "Christos Zafeiris",
            "Jakub Pešek",
            "Lukáš Červ",
        ],
        "CUW": [
            "Leandro Bacuna",
            "Jurgen Locadia",
            "Brandley Kuwas",
            "Gervane Kastaneer",
            "Diego Biseswar",
            "Rangelo Janga",
            "Elson Hooi",
            "Joshua Brenet",
            "Nigel Thomas",
            "Juninho Bacuna",
            "Vidar Kjartansson",
            "Kenji Görë",
            "Anthony van den Hurk",
            "Godfried Roemeratoe",
            "Jarchinio Antonia",
            "Gevaro Nepomuceno",
            "Roshon Distributie",
            "Jean-David Leaura",
            "Jurandy Martina",
            "Vurnon Anita",
            "Darryl Lachman",
            "Jairzinho Pie",
            "Charlison Benschop",
            "Quenten Martinus",
            "Jurensley Martina",
        ],
        "ECU": [
            "Moises Caicedo",
            "Enner Valencia",
            "Jeremy Sarmiento",
            "Gonzalo Plata",
            "Piero Hincapié",
            "Kendry Páez",
            "Joao Ortiz",
            "John Yeboah",
            "Alan Franco",
            "Ángel Mena",
            "Romario Ibarra",
            "Michael Estrada",
            "Jordy Caicedo",
            "Djorkaeff Reasco",
            "Kevin Rodríguez",
            "Jan Carlos Hurtado",
            "Joel Ordóñez",
            "William Pacho",
            "Felix Torres",
            "Robert Arboleda",
            "Jackson Porozo",
            "Pervis Estupiñán",
            "Moisés Ramírez",
            "Hernán Galíndez",
            "Carlos Gruezo",
        ],
        "EGY": [
            "Mohamed Salah",
            "Mostafa Mohamed",
            "Omar Marmoush",
            "Trézéguet",
            "Ramadan Sobhi",
            "Ahmed Hassan Kouka",
            "Omar Gaber",
            "Mohamed Elneny",
            "Hamdi Fathi",
            "Mohamed Abdelmonem",
            "Ahmed Hegazi",
            "Ali Gabr",
            "Ramy Rabia",
            "Mohamed Sherif",
            "Ibrahim Adel",
            "Mahmoud Hamada",
            "Osama Faisal",
            "Marwan Attia",
            "Emam Ashour",
            "Mohamed Abou Gabal",
            "Ahmed Sayed Zizo",
            "Hussein El Shahat",
            "Ayman Ashraf",
            "Mohamed Hany",
            "Ali Gholizadeh",
        ],
        "ENG": [
            "Harry Kane",
            "Jude Bellingham",
            "Phil Foden",
            "Bukayo Saka",
            "Marcus Rashford",
            "Jack Grealish",
            "Cole Palmer",
            "Ollie Watkins",
            "Ivan Toney",
            "Eberechi Eze",
            "James Maddison",
            "Declan Rice",
            "Kieran Trippier",
            "Luke Shaw",
            "John Stones",
            "Harry Maguire",
            "Trent Alexander-Arnold",
            "Kyle Walker",
            "Reece James",
            "Ben Chilwell",
            "Jarrod Bowen",
            "Anthony Gordon",
            "Callum Wilson",
            "Dominic Solanke",
            "Conor Gallagher",
        ],
        "ESP": [
            "Álvaro Morata",
            "Lamine Yamal",
            "Nico Williams",
            "Dani Olmo",
            "Ferran Torres",
            "Mikel Oyarzabal",
            "Gerard Moreno",
            "Joselu",
            "Rodri",
            "Pedri",
            "Gavi",
            "Fabián Ruiz",
            "Mikel Merino",
            "Dani Ceballos",
            "Álex Baena",
            "Marc Cucurella",
            "Aymeric Laporte",
            "Unai Simón",
            "Robin Le Normand",
            "Nacho Fernández",
            "Jesús Navas",
            "Pau Torres",
            "Eric García",
            "Vivian",
            "Oihan Sancet",
        ],
        "FRA": [
            "Kylian Mbappé",
            "Olivier Giroud",
            "Antoine Griezmann",
            "Ousmane Dembélé",
            "Kingsley Coman",
            "Marcus Thuram",
            "Randal Kolo Muani",
            "Bradley Barcola",
            "Eduardo Camavinga",
            "Aurélien Tchouaméni",
            "Adrien Rabiot",
            "Youssouf Fofana",
            "Warren Zaïre-Emery",
            "William Saliba",
            "Dayot Upamecano",
            "Jules Koundé",
            "Lucas Hernández",
            "Theo Hernández",
            "Ibrahima Konaté",
            "Benjamin Pavard",
            "Mike Maignan",
            "Jonathan Clauss",
            "Rayan Cherki",
            "Michael Olise",
            "Elye Wahi",
        ],
        "GHA": [
            "Mohammed Kudus",
            "Jordan Ayew",
            "André Ayew",
            "Iñaki Williams",
            "Antoine Semenyo",
            "Kamaldeen Sulemana",
            "Ernest Nuamah",
            "Osman Bukari",
            "Joseph Paintsil",
            "Daniel Afriyie",
            "Abdul Fatawu",
            "Thomas Partey",
            "Salis Abdul Samed",
            "Edmund Addo",
            "Mohammed Salisu",
            "Daniel Amartey",
            "Alexander Djiku",
            "Tariq Lamptey",
            "Alidu Seidu",
            "Joseph Aidoo",
            "Jojo Wollacott",
            "Richard Ofori",
            "Lawrence Ati-Zigi",
            "Felix Afena-Gyan",
            "Elisha Owusu",
        ],
        "GER": [
            "Jamal Musiala",
            "Florian Wirtz",
            "Kai Havertz",
            "Thomas Müller",
            "Niclas Füllkrug",
            "Serge Gnabry",
            "Leroy Sané",
            "Julian Brandt",
            "İlkay Gündoğan",
            "Leon Goretzka",
            "Joshua Kimmich",
            "Robert Andrich",
            "Emre Can",
            "Antonio Rüdiger",
            "Jonathan Tah",
            "Niklas Süle",
            "Thilo Kehrer",
            "David Raum",
            "Robin Gosens",
            "Benjamin Henrichs",
            "Chris Führich",
            "Maximilian Beier",
            "Deniz Undav",
            "Kevin Schade",
            "Timo Werner",
        ],
        "HAI": [
            "Duckens Nazon",
            "Frantzdy Pierrot",
            "Derrick Etienne Jr",
            "Carnejy Antoine",
            "Mondy Prunier",
            "Roberto Louima",
            "Steeven Saba",
            "Carlens Arcus",
            "Alex Junior Christian",
            "Fafa Picault",
            "Djimy Bendé",
            "Mikaël Cantave",
            "Don Louïse",
            "Bradley Legget",
            "Ricardo Adé",
            "Martin Expérience",
            "Manuel Nazareth",
            "Bryan Labissière",
            "Widler Metellus",
            "Alexandre Jr",
            "Dutherson Romain",
            "Jeppe",
            "Simson",
            "Melchie Dumornay",
            "Danielle Étienne",
        ],
        "IRN": [
            "Sardar Azmoun",
            "Mehdi Taremi",
            "Saman Ghoddos",
            "Alireza Jahanbakhsh",
            "Karim Ansarifard",
            "Ali Gholizadeh",
            "Aaron Boupendza",
            "Vahid Amiri",
            "Ehsan Hajsafi",
            "Milad Mohammadi",
            "Saeid Ezatolahi",
            "Omid Noorafkan",
            "Ali Karimi",
            "Shahriar Moghanlou",
            "Amir Abedzadeh",
            "Alireza Beiranvand",
            "Hossein Hosseini",
            "Payam Niazmand",
            "Ramin Rezaeian",
            "Shoja Khalilzadeh",
            "Hossein Kanaani",
            "Majid Hosseini",
            "Rouzbeh Cheshmi",
            "Aref Aghasi",
            "Jafar Salmani",
        ],
        "IRQ": [
            "Mohanad Ali",
            "Aymen Hussein",
            "Ali Jasim",
            "Mohanad Jeahze",
            "Amjad Attwan",
            "Ibrahim Bayesh",
            "Dhurgham Ismail",
            "Rebin Sulaka",
            "Saad Natiq",
            "Ali Adnan",
            "Mohammed Salih",
            "Ahmed Yasin",
            "Aso Rostam",
            "Zaid Tahseen",
            "Merchas Doski",
            "Humam Tariq",
            "Ahmad Farhan",
            "Bashar Resan",
            "Justin Meram",
            "Youssef Amyn",
            "Mustafa Mohammed",
            "Ali Husni",
            "Safaa Hadi",
            "Osama Rashid",
            "Mohammed Dawood",
        ],
        "JOR": [
            "Musa Al-Taamari",
            "Yazan Al-Naimat",
            "Ali Olwan",
            "Yazan Al-Arab",
            "Mahmoud Mardi",
            "Anas Bani Yaseen",
            "Baraa Marei",
            "Salem Al-Ajalin",
            "Yousef Abu Jalboush",
            "Mohammad Abu Hashish",
            "Noor Al-Rawabdeh",
            "Yousef Shloul",
            "Yousef Abu Zaid",
            "Ahmed Samir",
            "Ihsan Haddad",
            "Firas Al-Sharaa",
            "Monther Abu Amarah",
            "Saad Al-Rousan",
            "Raja Al-Farra",
            "Yaser Hamed",
            "Ahmed Alireza",
            "Ahmed Sariweh",
            "Nizar Al-Rashdan",
            "Yousef Aymen",
            "Saleh Rateb",
        ],
        "JPN": [
            "Takefusa Kubo",
            "Kaoru Mitoma",
            "Junya Ito",
            "Ayase Ueda",
            "Daizen Maeda",
            "Takumi Minamino",
            "Ritsu Doan",
            "Kyogo Furuhashi",
            "Keito Nakamura",
            "Daichi Kamada",
            "Wataru Endo",
            "Takehiro Tomiyasu",
            "Ko Itakura",
            "Hiroki Ito",
            "Koki Machida",
            "Ao Tanaka",
            "Hidemasa Morita",
            "Reo Hatate",
            "Shuto Machino",
            "Yukinari Sugawara",
            "Keisuke Osako",
            "Zion Suzuki",
            "Kota Takai",
            "Yuta Nakayama",
            "Miki Yamane",
        ],
        "KOR": [
            "Son Heung-min",
            "Hwang Hee-chan",
            "Lee Kang-in",
            "Cho Gue-sung",
            "Hwang Ui-jo",
            "Oh Hyeon-gyu",
            "Jeong Woo-yeong",
            "Hong Hyun-seok",
            "Hwang In-beom",
            "Paik Seung-ho",
            "Son Jun-ho",
            "Kim Jin-su",
            "Kim Min-jae",
            "Kim Young-gwon",
            "Seol Young-woo",
            "Lee Ki-je",
            "Jung Seung-hyun",
            "Kim Moon-hwan",
            "Kim Tae-hwan",
            "Na Sang-ho",
            "Yang Hyun-jun",
            "Lee Jae-sung",
            "Um Won-sang",
            "Park Yong-woo",
            "Lee Soon-min",
        ],
        "KSA": [
            "Salem Al-Dawsari",
            "Firas Al-Buraikan",
            "Saleh Al-Shehri",
            "Fahad Al-Muwallad",
            "Saud Abdulhamid",
            "Ali Al-Hassan",
            "Mohammed Kanno",
            "Abdulelah Al-Malki",
            "Hassan Tambakti",
            "Ali Lajami",
            "Ali Bulayhi",
            "Sultan Al-Ghannam",
            "Mohammed Al-Burayk",
            "Yasir Al-Shahrani",
            "Ayman Yahya",
            "Nawaf Al-Abed",
            "Abdullah Radif",
            "Abdullah Al-Hamdan",
            "Abdullah Otayf",
            "Ibrahim Ghaleb",
            "Khalid Al-Ghannam",
            "Mohammed Majrashi",
            "Rayane Hamidou",
            "Talal Haji",
            "Haitham Asiri",
        ],
        "MAR": [
            "Achraf Hakimi",
            "Youssef En-Nesyri",
            "Sofiane Boufal",
            "Hakim Ziyech",
            "Azzedine Ounahi",
            "Selim Amallah",
            "Noussair Mazraoui",
            "Nayef Aguerd",
            "Roman Saïss",
            "Jawad El Yamiq",
            "Sofyan Amrabat",
            "Amine Harit",
            "Walid Cheddira",
            "Abde Ezzalzouli",
            "Youssef Maleh",
            "Bilal El Khannous",
            "Ez Abde",
            "Chadi Riad",
            "Ilias Chair",
            "Tarik Tissoudali",
            "Zakaria Aboukhlal",
            "Soufiane Rahimi",
            "Ayoub El Kaabi",
            "Abdessamad Ezzalzouli",
            "Amine Adli",
        ],
        "MEX": [
            "Santiago Giménez",
            "Raúl Jiménez",
            "Henry Martín",
            "Uriel Antuna",
            "Roberto Alvarado",
            "Hirving Lozano",
            "Alexis Vega",
            "Orbelín Pineda",
            "Julián Quiñones",
            "Diego Lainez",
            "Jesús Gallardo",
            "Luis Romo",
            "Edson Álvarez",
            "Luis Chávez",
            "Carlos Rodríguez",
            "Jorge Sánchez",
            "Johan Vásquez",
            "César Montes",
            "Jesús Orozco",
            "Marcelo Flores",
            "Jordi Cortizo",
            "Erick Sánchez",
            "Santi Muñoz",
            "Ozziel Herrera",
            "Gilberto Mora",
        ],
        "NED": [
            "Memphis Depay",
            "Cody Gakpo",
            "Wout Weghorst",
            "Steven Bergwijn",
            "Brian Brobbey",
            "Jerdy Schouten",
            "Xavi Simons",
            "Frenkie de Jong",
            "Georginio Wijnaldum",
            "Teun Koopmeiners",
            "Tijjani Reijnders",
            "Donyell Malen",
            "Virgil van Dijk",
            "Nathan Aké",
            "Denzel Dumfries",
            "Jurriën Timber",
            "Matthijs de Ligt",
            "Stefan de Vrij",
            "Micky van de Ven",
            "Lutsharel Geertruida",
            "Andries Noppert",
            "Bart Verbruggen",
            "Quinten Timber",
            "Noa Lang",
            "Justin Kluivert",
        ],
        "NOR": [
            "Erling Haaland",
            "Alexander Sørloth",
            "Oscar Bobb",
            "Martin Ødegaard",
            "Antonio Nusa",
            "Jørgen Strand Larsen",
            "Joshua King",
            "Sander Berge",
            "Kristian Thorstvedt",
            "Fredrik Aursnes",
            "Patrick Berg",
            "Morten Thorsby",
            "Thomas Rogne",
            "Leo Skiri Østigård",
            "Kristoffer Ajer",
            "Stian Gregersen",
            "Marcus Pedersen",
            "Julian Ryerson",
            "Fredrik Bjørkan",
            "Ørjan Nyland",
            "Aron Dønnum",
            "Halldor Stenevik",
            "Tobias Christensen",
            "Erik Botheim",
            "Lars Olden Larsen",
        ],
        "NZL": [
            "Chris Wood",
            "Ben Waine",
            "Marco Rojas",
            "Matthew Garbett",
            "Ben Old",
            "Marko Stamenic",
            "Joe Bell",
            "Sarpreet Singh",
            "Liberato Cacace",
            "Nando Pijnaker",
            "Tim Payne",
            "Callan Elliot",
            "Dane Ingham",
            "Winston Reid",
            "Michael Boxall",
            "Tommy Smith",
            "Francis de Vries",
            "Fin Conchie",
            "Finn Surman",
            "Oliver Sail",
            "Max Crocombe",
            "Alex Paulsen",
            "Kosta Barbarouses",
            "Logan Rogerson",
            "Elijah Just",
        ],
        "PAN": [
            "Aníbal Godoy",
            "Michael Murillo",
            "Eric Davis",
            "Fidel Escobar",
            "Ismael Díaz",
            "Alberto Quintero",
            "Gabriel Torres",
            "José Fajardo",
            "Rolando Blackburn",
            "César Yanis",
            "Azarías Londoño",
            "Édgar Bárcenas",
            "Jorman Aguilar",
            "Yoel Bárcenas",
            "Cecilio Waterman",
            "Abdiel Arroyo",
            "Harold Cummings",
            "Roberto Nurse",
            "Luis Mejía",
            "Orlando Mosquera",
            "Álex Rodríguez",
            "Alfredo Stephens",
            "Iván Anderson",
            "Kevin Galván",
            "Omár Browne",
        ],
        "PAR": [
            "Miguel Almirón",
            "Julio Enciso",
            "Antonio Sanabria",
            "Ángel Romero",
            "Óscar Romero",
            "Diego Gómez",
            "Mathías Villasanti",
            "André Cubas",
            "Richard Sánchez",
            "Blas Riveros",
            "Santiago Arzamendia",
            "Gustavo Gómez",
            "Junior Alonso",
            "Fabrizio Peralta",
            "Hernán Pérez",
            "Ramón Miño",
            "Álvaro Oviedo",
            "Robert Morales",
            "Tonny Sanabria",
            "Adam Bareiro",
            "Hugo Fernández",
            "Gabriel Avalos",
            "Kaku Romero",
            "Álex Arce",
            "Diego León",
        ],
        "POR": [
            "Cristiano Ronaldo",
            "Bruno Fernandes",
            "Bernardo Silva",
            "João Félix",
            "Rafael Leão",
            "Gonçalo Ramos",
            "Diogo Jota",
            "Vitinha",
            "Rúben Neves",
            "Danilo Pereira",
            "Otávio",
            "João Palhinha",
            "Rúben Dias",
            "João Cancelo",
            "Nuno Mendes",
            "Pepe",
            "Diogo Dalot",
            "Gonçalo Inácio",
            "António Silva",
            "João Mário",
            "André Silva",
            "Francisco Conceição",
            "Jota Silva",
            "Ricardo Horta",
            "Paulinho",
        ],
        "QAT": [
            "Akram Afif",
            "Almoez Ali",
            "Hassan Al-Haydos",
            "Abdulaziz Hatem",
            "Karim Boudiaf",
            "Assim Madibo",
            "Homam Ahmed",
            "Abdelkarim Hassan",
            "Boualem Khoukhi",
            "Tarek Salman",
            "Pedro Miguel",
            "Abdullah Al-Ahrak",
            "Ahmed Alaaeldin",
            "Mustafa Mashaal",
            "Ali Asad",
            "Musab Ahmed",
            "Yousef Hassan",
            "Meshaal Aissa",
            "Khalid Muneer",
            "Naif Al-Hadhrami",
            "Salman Al-Farsi",
            "Saad Al Sheeb",
            "Meshaal Barsham",
            "Yusuf Abdurisag",
            "Ahmed Alaa",
        ],
        "RSA": [
            "Percy Tau",
            "Themba Zwane",
            "Lyle Foster",
            "Lebo Mothiba",
            "Oswin Appolis",
            "Evidence Makgopa",
            "Zakhele Lepasa",
            "Mihlali Mayambela",
            "Sphephelo Sithole",
            "Teboho Mokoena",
            "Siyethemba Sithebe",
            "Aubrey Modiba",
            "Terence Mashego",
            "Khuliso Mudau",
            "Siyanda Xulu",
            "Nyiko Mobbie",
            "Grant Kekana",
            "Mothobi Mvala",
            "Thapelo Morena",
            "Ronwen Williams",
            "Veli Mothwa",
            "Sage Stephens",
            "Raymond Monare",
            "Jayden Adams",
            "Ethan Brooks",
        ],
        "SCO": [
            "Scott McTominay",
            "John McGinn",
            "Lyndon Dykes",
            "Che Adams",
            "Lawrence Shankland",
            "Billy Gilmour",
            "Ryan Christie",
            "Callum McGregor",
            "Lewis Ferguson",
            "Kenny McLean",
            "Kieran Tierney",
            "Andy Robertson",
            "Aaron Hickey",
            "Nathan Patterson",
            "Jack Hendry",
            "Ryan Porteous",
            "Grant Hanley",
            "Liam Cooper",
            "Scott Bain",
            "Angus Gunn",
            "Zander Clark",
            "Greg Taylor",
            "Josh Doig",
            "Ben Doak",
            "Lewis Morgan",
        ],
        "SEN": [
            "Sadio Mané",
            "Nicolas Jackson",
            "Ismaïla Sarr",
            "Boulaye Dia",
            "Habib Diallo",
            "Cheikhou Kouyaté",
            "Idrissa Gueye",
            "Pape Matar Sarr",
            "Pathé Ciss",
            "Krépin Diatta",
            "Kalidou Koulibaly",
            "Abdou Diallo",
            "Formose Mendy",
            "Youssouf Sabaly",
            "Fodé Ballo-Touré",
            "Bouna Sarr",
            "Iliman Ndiaye",
            "Abdoulaye Seck",
            "Moussa Niakhaté",
            "Pape Gueye",
            "Lamine Camara",
            "Habib Diarra",
            "Nampalys Mendy",
            "Alfred Gomis",
            "Mory Diaw",
        ],
        "SUI": [
            "Breel Embolo",
            "Noah Okafor",
            "Ruben Vargas",
            "Xherdan Shaqiri",
            "Granit Xhaka",
            "Remo Freuler",
            "Denis Zakaria",
            "Michel Aebischer",
            "Fabian Rieder",
            "Mohamed Amdouni",
            "Zeki Amdouni",
            "Yann Sommer",
            "Gregor Kobel",
            "Manuel Akanji",
            "Nico Elvedi",
            "Ricardo Rodriguez",
            "Silvan Widmer",
            "Edimilson Fernandes",
            "Renato Steffen",
            "Christian Fassnacht",
            "Ayumu Seko",
            "Vincent Sierro",
            "Andy Zeqiri",
            "Kwadwo Duah",
            "Dan Ndoye",
        ],
        "SWE": [
            "Alexander Isak",
            "Victor Gyökeres",
            "Dejan Kulusevski",
            "Robin Quaison",
            "Jordan Larsson",
            "Anthony Elanga",
            "Jesper Karlsson",
            "Emil Forsberg",
            "Mattias Svanberg",
            "Kristoffer Olsson",
            "Albin Ekdal",
            "Ludwig Augustinsson",
            "Victor Lindelöf",
            "Emil Holm",
            "Isak Hien",
            "Gustaf Lagerbielke",
            "Arnór Ingvi Traustason",
            "Sebastian Nanasi",
            "Yasin Ayari",
            "Robin Olsen",
            "Kristoffer Nordfeldt",
            "Alexander Bernsson",
            "Danielson",
            "Jens Cajuste",
            "Niclas Eliasson",
        ],
        "TUN": [
            "Youssef Msakni",
            "Seifeddine Jaziri",
            "Anis Ben Slimane",
            "Elias Achouri",
            "Wahbi Khazri",
            "Naïm Sliti",
            "Hamza Rafia",
            "Aissa Laïdouni",
            "Ali Abdi",
            "Montassar Talbi",
            "Yann Valery",
            "Ali Maâloul",
            "Wajdi Kechrida",
            "Bilel Ifa",
            "Yassine Meriah",
            "Dylan Bronn",
            "Mohamed Dräger",
            "Bechir Ben Said",
            "Aymen Dahmen",
            "Haythem Jouini",
            "Bassem Srarfi",
            "Ferjani Sassi",
            "Mohamed Ali Ben Romdhane",
            "Seifeddine Jebali",
            "Taha Yassine Khenissi",
        ],
        "TUR": [
            "Hakan Çalhanoğlu",
            "Arda Güler",
            "Kerem Aktürkoğlu",
            "İrfan Can Kahveci",
            "Cengiz Ünder",
            "Enes Ünal",
            "Kenan Yıldız",
            "Barış Alper Yılmaz",
            "Orkun Kökçü",
            "Salih Özcan",
            "Okay Yokuşlu",
            "Merih Demiral",
            "Çağlar Söyüncü",
            "Zeki Çelik",
            "Ferdi Kadıoğlu",
            "Mert Müldür",
            "Altay Bayındır",
            "Uğurcan Çakır",
            "Berkan Kutlu",
            "Halil Dervişoğlu",
            "Cenk Tosun",
            "Yusuf Yazıcı",
            "Deniz Türüç",
            "Yunus Akgün",
            "Kerem Demirbay",
        ],
        "USA": [
            "Christian Pulisic",
            "Folarin Balogun",
            "Ricardo Pepi",
            "Haji Wright",
            "Tim Weah",
            "Giovanni Reyna",
            "Weston McKennie",
            "Tyler Adams",
            "Yunus Musah",
            "Luca de la Torre",
            "Malik Tillman",
            "Brenden Aaronson",
            "Alejandro Zendejas",
            "Jordan Morris",
            "Cade Cowell",
            "Konrad de la Fuente",
            "Josh Sargent",
            "Jesus Ferreira",
            "Djordje Mihailovic",
            "Kristoffer Lund",
            "Sergiño Dest",
            "Antonee Robinson",
            "Miles Robinson",
            "Matt Turner",
            "Ethan Horvath",
        ],
        "URU": [
            "Darwin Núñez",
            "Luis Suárez",
            "Edinson Cavani",
            "Federico Valverde",
            "Giorgian de Arrascaeta",
            "Rodrigo Bentancur",
            "Nicolás Lodeiro",
            "Matías Vecino",
            "Lucas Torreira",
            "Manuel Ugarte",
            "Carlos Benavídez",
            "Brian Rodríguez",
            "Agustín Canobbio",
            "Facundo Pellistri",
            "Maxi Gómez",
            "Jonathan Rodríguez",
            "Josema Giménez",
            "Ronald Araujo",
            "Sebastián Coates",
            "Martín Cáceres",
            "Matías Viña",
            "Guillermo Varela",
            "Santiago Mele",
            "Sergio Rochet",
            "Fernando Muslera",
        ],
        "UZB": [
            "Jaloliddin Masharipov",
            "Eldor Shomurodov",
            "Igor Sergeev",
            "Oston Urunov",
            "Azizbek Turgunboev",
            "Khojakbar Alijonov",
            "Farrukh Sayfiev",
            "Rustamjon Ashurmatov",
            "Abdukodir Khusanov",
            "Sherzod Nasrullaev",
            "Umarbek Eshmurodov",
            "Odiljon Hamrobekov",
            "Oybek Bozorov",
            "Jamshid Iskanderov",
            "Azizbek Amonov",
            "Abbosbek Fayzullaev",
            "Diyor Kholmatov",
            "Ruslanbek Jiyanov",
            "Utkir Yusupov",
            "Lutfulla Turaev",
            "Mutal Nazarov",
            "Bobur Abdikholikov",
            "Azizbek Khayrov",
            "Husniddin Aliqulov",
            "Shokhboz Umarov",
        ],
    }

    for c in codes:
        if c not in pools:
            raise SystemExit(f"missing pool for {c}")
        if len(pools[c]) != 25:
            raise SystemExit(f"{c} has {len(pools[c])} names, need 25")
        # dedupe within country (case-insensitive)
        seen: set[str] = set()
        clean: list[str] = []
        for n in pools[c]:
            k = n.strip().lower()
            if not k or k in seen:
                continue
            seen.add(k)
            clean.append(n.strip())
        while len(clean) < 25:
            clean.append(f"{c} squad depth {len(clean) + 1}")
        pools[c] = clean[:25]

    out = {c: pools[c] for c in codes}
    dest = _REPO / "worldcup_pool" / "data" / "wc2026_top_scorer_candidates.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print("wrote", dest, "keys", len(out))


if __name__ == "__main__":
    main()
